
#ifndef _RUPERTS_NOPERT229_H
#define _RUPERTS_NOPERT229_H

#include <array>

#include "bignum/big-vec.h"
#include "bignum/big.h"
#include "yocto-math.h"

// ============================================================================
// MATHEMATICAL BACKGROUND & COORDINATE REPRESENTATION:
//
// 1. Continuous C5 Model vs. Discrete Rational Polyhedron:
//    - The idealized geometric counterexample candidate #229 has continuous
//      5-fold rotational symmetry (C5) about the z-axis generated by rotating
//      4 seed vertices:
//        seed 0 (top cap), seed 1 (upper ring), seed 2 (middle ring), seed 3 (lower ring)
//      by increments of 2*pi/5 (72 degrees).
//    - The rotation matrix R_z(2*pi/5) involves cos(2*pi/5) = (sqrt(5) - 1)/4
//      and sin(2*pi/5) = sqrt((5 + sqrt(5))/8). These trigonometric values are
//      irrational algebraic numbers in Q(sqrt(5), sqrt(10 + 2*sqrt(5))).
//    - Consequently, even if seed vertices 0..3 have exact rational (or algebraic)
//      coordinates, their continuous C5 orbit points for k in {1, 2, 3, 4} are
//      IRRATIONAL in R^3 and cannot be represented exactly in Q^3.
//
// 2. The Frozen Rational Polytope in Lean 4 and C++ Tools:
//    - The Rupert/Nopert property is certified over a SPECIFIC, RIGID rational
//      polyhedron P in Q^3 with exactly 20 vertices.
//    - To avoid algebraic number fields and keep Lean 4 kernel verification
//      fast, decodable, and certified via exact rational Farkas cages, the 20
//      vertices are frozen as fixed rational numbers in Q^3.
//    - Vertices 0..3 are the rational seed points.
//    - Vertices 4..19 are high-precision rational approximations (matching to
//      16 decimal digits, error < 3e-16) to the continuous C5 orbit points.
//    - In Lean (Noperthedron.Nopert229.Vertices), the formalization defines both:
//        a) `exactVertex` in R^3: continuous C5 rotation of the 4 seed vertices.
//        b) `rationalVertices` in Q^3: the frozen rational coordinates below.
//      Lean proves bounds between the rational polyhedron and the ideal continuous
//      model, while our identity tube certification operates directly and strictly
//      on the rational polyhedron P.
//
// 3. Double-Precision Floating Point (VERTICES):
//    - The double array `VERTICES` contains IEEE-754 binary64 approximations
//      matching the exact rational fractions `VERTICES_Q` to < 1e-15 precision.
//    - Both double and rational representations exhibit approximate C5 symmetry
// ============================================================================
// NOTE / REGENERATION:
// The canonical 27-facet rational coordinates with power-of-two denominators
// (2^52) and exact quad planarization (defect = 0 in Q^3) are implemented in
// ruperts/codebdd229.cc (GenerateBestPossibleRationalVertices).
// Drop-in replacements are generated at:
//   - C++:  vertices229_exact27.h
//   - Lean: vertices229_exact27.lean
//   - JSON: vertices229_exact27.json
// See noteperts/QUAD_FACES.md for full analysis and derivation.
// ============================================================================

// 20 vertices of Nopert #229, derived algebraically from repair214.cc
// and scaled strictly inside the unit sphere for Lean's GoodPoly invariant.
inline constexpr int NUM_VERTICES = 20;
inline constexpr double VERTICES[NUM_VERTICES][3] = {
  {  0.0428407320766475,  0.5680663556187131,  0.5648167326177671 }, // 0
  { -0.1710940528198280,  0.9384169756351713,  0.3001672949030625 }, // 1
  { -0.2791996671138589,  0.8916783831939151, -0.0420605170858861 }, // 2
  {  0.0581211699562287,  0.6025790913331870, -0.7643399516054460 }, // 3

  { -0.5270246949360691,  0.2162861152231751,  0.5648167326177671 }, // 4
  { -0.9453585496376318,  0.1272666794475643,  0.3001672949030625 }, // 5
  { -0.9343139787381105,  0.0100091111676232, -0.0420605170858861 }, // 6
  { -0.5551263421462106,  0.2414836970985378, -0.7643399516054460 }, // 7

  { -0.3685599064576828, -0.4343941851161148,  0.5648167326177671 }, // 8
  { -0.4131696624115331, -0.8597618421012388,  0.3001672949030625 }, // 9
  { -0.2982381279104400, -0.8854924122951479, -0.0420605170858861 }, // 10
  { -0.4012081174529903, -0.4533339587973062, -0.7643399516054460 }, // 11

  {  0.2992421458547392, -0.4847564861402479,  0.5648167326177671 }, // 12
  {  0.6900056551469845, -0.6586287200963504,  0.3001672949030625 }, // 13
  {  0.7499926789483198, -0.5572735187461599, -0.0420605170858861 }, // 14
  {  0.3071660889979028, -0.5216594918898176, -0.7643399516054460 }, // 15

  {  0.5535017234623651,  0.1347982004144742,  0.5648167326177671 }, // 16
  {  0.8396166097220085,  0.4527069071148534,  0.3001672949030625 }, // 17
  {  0.7617590948140895,  0.5410784366797694, -0.0420605170858861 }, // 18
  {  0.5910472006450693,  0.1309306622553988, -0.7643399516054460 }  // 19
};

inline constexpr yocto::vec<double, 3> Vertex(size_t v) {
  return yocto::vec<double, 3>{
    VERTICES[v][0],
    VERTICES[v][1],
    VERTICES[v][2],
  };
}

// Get BigRat vertices (singleton).
// Deprecated!
const std::array<std::array<BigRat, 3>, NUM_VERTICES> &GetVerticesQ();

const BigVecQ3 &VertexQ(size_t v);

#endif
