#!/bin/bash

# ./render.sh tilteddecagonpyramid
# ./render.sh squatsnail
# ./render.sh flattenedicosahedron
# ./render.sh longtaperedprism
# ./render.sh longtaperedantiprism
# ./render.sh lowpolylens
# ./render.sh coin
# ./render.sh sawblade
# ./render.sh dome
# ./render.sh chisel
# ./render.sh cigar
# ./render.sh rubikscube
./render.sh truncatedwedge
./render.sh rectifiedwedge

# ./render.sh j1
# ./render.sh j2
# ./render.sh j3
# ./render.sh j4
# ./render.sh j5
# ./render.sh j6
# ./render.sh j7
# ./render.sh j8
# ./render.sh j9
# ./render.sh j10
# ./render.sh j11
# ./render.sh j12
# ./render.sh j13
# ./render.sh j14
# ./render.sh j15
# ./render.sh j16
# ./render.sh j17
# ./render.sh j18
# ./render.sh j19
# ./render.sh j20
# ./render.sh j21
# ./render.sh j22
# ./render.sh j23
# ./render.sh j24
# ./render.sh j25
# ./render.sh j26
# ./render.sh j27
# ./render.sh j28
# ./render.sh j29
# ./render.sh j30
# ./render.sh j31
# ./render.sh j32
# ./render.sh j33
# ./render.sh j34
# ./render.sh j35
# ./render.sh j36
# ./render.sh j37
# ./render.sh j38
# ./render.sh j39
# ./render.sh j40
# ./render.sh j41
# ./render.sh j42
# ./render.sh j43
# ./render.sh j44
# ./render.sh j45
# ./render.sh j46
# ./render.sh j47
# ./render.sh j48
# ./render.sh j49
# ./render.sh j50
# ./render.sh j51
# ./render.sh j52
# ./render.sh j53
# ./render.sh j54
# ./render.sh j55
# ./render.sh j56
# ./render.sh j57
# ./render.sh j58
# ./render.sh j59
# ./render.sh j60
# ./render.sh j61
# ./render.sh j62
# ./render.sh j63
# ./render.sh j64
# ./render.sh j65
# ./render.sh j66
# ./render.sh j67
# ./render.sh j68
# ./render.sh j69
# ./render.sh j70
# ./render.sh j71
# ./render.sh j72
# ./render.sh j73
# ./render.sh j74
# ./render.sh j75
# ./render.sh j76
# ./render.sh j77
# ./render.sh j78
# ./render.sh j79
# ./render.sh j80
# ./render.sh j81
# ./render.sh j82
# ./render.sh j83
# ./render.sh j84
# ./render.sh j85
# ./render.sh j86
# ./render.sh j87
# ./render.sh j88
# ./render.sh j89
# ./render.sh j90
# ./render.sh j91
# ./render.sh j92

# ./render.sh tetrahedron
# ./render.sh cube
# ./render.sh dodecahedron
# ./render.sh icosahedron
# ./render.sh octahedron
# ./render.sh truncatedtetrahedron
# ./render.sh cuboctahedron
# ./render.sh truncatedcube
# ./render.sh truncatedoctahedron
# ./render.sh rhombicuboctahedron
# ./render.sh truncatedcuboctahedron
# ./render.sh snubcube
# ./render.sh icosidodecahedron
# ./render.sh truncateddodecahedron
# ./render.sh truncatedicosahedron
# ./render.sh rhombicosidodecahedron
# ./render.sh truncatedicosidodecahedron
# ./render.sh snubdodecahedron
# ./render.sh triakistetrahedron
# ./render.sh rhombicdodecahedron
# ./render.sh triakisoctahedron
# ./render.sh tetrakishexahedron
# ./render.sh deltoidalicositetrahedron
# ./render.sh disdyakisdodecahedron
# ./render.sh deltoidalhexecontahedron
# ./render.sh pentagonalicositetrahedron
# ./render.sh rhombictriacontahedron
# ./render.sh triakisicosahedron
# ./render.sh pentakisdodecahedron
# ./render.sh disdyakistriacontahedron
# ./render.sh pentagonalhexecontahedron
# ./render.sh noperthedron
# ./render.sh onperthedron
