#include "talk.h"

#include <cstdio>
#include <cstdlib>
#include <memory>
#include <utility>
#include <string>
#include <vector>
#include <cstring>

#include "util.h"
#include "image.h"
#include "base/logging.h"
#include "base/stringprintf.h"

using namespace std;

Talk Talk::Load(const string &src_filename) {
  vector<string> src = Util::ReadFileToLines(src_filename);
  CHECK(!src.empty()) << src_filename << " empty / not found?";

  Talk talk;
  Slide *slide = nullptr;

  static constexpr int DEFAULT_DURATION = 2;
  int duration = DEFAULT_DURATION;
  for (string line : src) {
    string cmd = Util::chop(line);
    if (cmd == "#" || cmd == "")
      continue;

    auto AddFile = [&slide, &duration](const string &f) {
        slide->frames.emplace_back();
        Frame *frame = &slide->frames.back();
        frame->filename = f;
        frame->duration = duration;
      };

    if (cmd == "end") {
      printf("Ending early!\n");
      break;
    } else if (cmd == "slide") {
      talk.slides.emplace_back();
      slide = &talk.slides.back();
      duration = DEFAULT_DURATION;
    } else if (cmd == "dur") {
      string d = Util::chop(line);
      CHECK(slide != nullptr) << "start slide first";
      duration = atoi(d.c_str());
      CHECK(duration > 0) << "got: " << d;
    } else if (cmd == "array") {
      CHECK(slide != nullptr) << "start slide first";
      string los = Util::chop(line);
      string his = Util::chop(line);
      string f = Util::chop(line);
      CHECK(!f.empty() && f.find("%") != string::npos) << "array: " << f;
      int lo = atoi(los.c_str());
      int hi = atoi(his.c_str());
      for (int x = lo; x <= hi; x++) {
        AddFile(Util::Replace(f, "%", StringPrintf("%d", x)));
      }
    } else {
      // Command must be a file that we can open.
      CHECK(slide != nullptr) << "start slide first (" << cmd << ")";
      AddFile(cmd);
    }
  }

  return talk;
}

void Talk::SaveJS(const string &dir) {
  std::string json = "/* Generated by talk.cc. Do not edit! */\n"
    "const slides = [\n";
  for (const Slide &slide : slides) {
    StringAppendF(&json, "  [");
    for (const Frame &frame : slide.frames) {
      std::string noext = (std::string)Util::FileBaseOf(frame.filename);
      StringAppendF(&json, "{i: '%s', d: %d}, ",
                    noext.c_str(), frame.duration);
    }
    StringAppendF(&json, "],\n");
  }
  StringAppendF(&json, "];\n");

  Util::WriteFile(Util::dirplus(dir, "slides.js"), json);

  Util::WriteFile(Util::dirplus(dir, "talk.html"),
                  Util::ReadFile("talk.html"));
}
