#include "talk.h"

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "util.h"
#include "base/logging.h"
#include "base/stringprintf.h"

using namespace std;

Talk Talk::Load(const string &src_filename) {
  vector<string> src = Util::ReadFileToLines(src_filename);
  CHECK(!src.empty()) << src_filename << " empty / not found?";

  Talk talk;
  Slide *slide = nullptr;

  static constexpr int DEFAULT_DURATION = 2;
  int duration = DEFAULT_DURATION;
  for (string line : src) {
    string cmd = Util::chop(line);
    if (cmd == "#" || cmd == "")
      continue;

    auto AddFile = [&slide, &duration](const string &f) {
        slide->frames.emplace_back();
        Frame *frame = &slide->frames.back();
        frame->filename = f;
        frame->duration = duration;
      };

    if (cmd == "end") {
      printf("Ending early!\n");
      break;

    } else if (cmd == "slide") {
      talk.slides.emplace_back();
      slide = &talk.slides.back();
      duration = DEFAULT_DURATION;

    } else if (cmd == "video") {
      CHECK(slide != nullptr) << "video: start slide first";
      CHECK(!slide->video.has_value()) << "Just one video per slide is "
        "currently supported.";
      int x = atoi(Util::chop(line).c_str());
      int y = atoi(Util::chop(line).c_str());
      int w = atoi(Util::chop(line).c_str());
      int h = atoi(Util::chop(line).c_str());
      string src = Util::chop(line);
      CHECK(!src.empty()) << "Video needs src.";
      slide->video.emplace(Video{.x = x, .y = y, .width = w, .height = h,
          .src = src});

    } else if (cmd == "dur") {
      string d = Util::chop(line);
      CHECK(slide != nullptr) << "dur: start slide first";
      duration = atoi(d.c_str());
      CHECK(duration > 0) << "got: " << d;

    } else if (cmd == "loop-video") {
      CHECK(slide != nullptr) << "loop-video: Add a slide first.";
      CHECK(slide->video.has_value()) << "Add a video to the slide "
        "first.";
      slide->video.value().loop = true;

    } else if (cmd == "target") {
      CHECK(slide != nullptr) << "target: Add a slide first.";
      string sec = Util::chop(line);
      slide->target_seconds = atoi(sec.c_str());

    } else if (cmd == "array") {
      CHECK(slide != nullptr) << "array: start slide first";
      string los = Util::chop(line);
      string his = Util::chop(line);
      string f = Util::chop(line);
      CHECK(!f.empty() && f.find("%") != string::npos) << "array: " << f;
      int lo = atoi(los.c_str());
      int hi = atoi(his.c_str());
      for (int x = lo; x <= hi; x++) {
        AddFile(Util::Replace(f, "%", StringPrintf("%d", x)));
      }
    } else {
      // Command must be a file that we can open.
      CHECK(slide != nullptr) << "start slide first (" << cmd << ")";
      AddFile(cmd);
    }
  }

  return talk;
}

void Talk::SaveJS(const string &dir) {
  std::string json = "/* Generated by talk.cc. Do not edit! */\n"
    "const slides = [\n";
  for (const Slide &slide : slides) {
    StringAppendF(&json, "  {a: [");

    for (const Frame &frame : slide.frames) {
      std::string noext = (std::string)Util::FileBaseOf(frame.filename);
      StringAppendF(&json, "{i: '%s', d: %d}, ",
                    noext.c_str(), frame.duration);
    }
    StringAppendF(&json, "]");
    if (slide.video.has_value()) {
      const Video &v = slide.video.value();
      StringAppendF(&json,
                    ", video: { x: %d, y: %d, w: %d, h: %d, src: '%s'",
                    v.x, v.y, v.width, v.height, v.src.c_str());
      if (v.loop) {
        StringAppendF(&json, ", loop: true");
      }
      StringAppendF(&json, "}");
    }

    if (slide.target_seconds > 0) {
      StringAppendF(&json,
                    ", target: %d",
                    slide.target_seconds);
    }

    StringAppendF(&json, "},\n");
  }
  StringAppendF(&json, "];\n");

  Util::WriteFile(Util::dirplus(dir, "slides.js"), json);

  Util::WriteFile(Util::dirplus(dir, "talk.html"),
                  Util::ReadFile("talk.html"));
  // This should be configured in the talk?
  Util::WriteFile(Util::dirplus(dir, "mouse-cursor.png"),
                  Util::ReadFile("mouse-cursor.png"));
}
