#include "talk.h"

#include <cstdlib>
#include <format>
#include <string>
#include <string_view>
#include <vector>

#include "base/logging.h"
#include "base/print.h"
#include "base/stringprintf.h"
#include "util.h"

using namespace std;

Talk Talk::Load(string_view src_filename) {
  vector<string> src = Util::ReadFileToLines(src_filename);
  CHECK(!src.empty()) << src_filename << " empty / not found?";

  Talk talk;
  Slide *slide = nullptr;

  static constexpr int DEFAULT_DURATION = 2;
  int duration = DEFAULT_DURATION;
  for (string line : src) {
    string cmd = Util::chop(line);
    if (cmd == "#" || cmd == "")
      continue;

    auto AddFile = [&slide, &duration](const string &f) {
        slide->frames.emplace_back();
        Frame *frame = &slide->frames.back();
        frame->filename = f;
        frame->duration = duration;
      };

    if (cmd == "end") {
      Print("Ending early!\n");
      break;

    } else if (cmd == "slide") {
      talk.slides.emplace_back();
      slide = &talk.slides.back();
      duration = DEFAULT_DURATION;

    } else if (cmd == "video") {
      CHECK(slide != nullptr) << "video: start slide first";
      CHECK(!slide->video.has_value()) << "Just one video per slide is "
        "currently supported.";
      int x = atoi(Util::chop(line).c_str());
      int y = atoi(Util::chop(line).c_str());
      int w = atoi(Util::chop(line).c_str());
      int h = atoi(Util::chop(line).c_str());
      string src = Util::chop(line);
      CHECK(!src.empty()) << "Video needs src.";
      slide->video.emplace(Video{
          .x = x, .y = y,
          .width = w, .height = h,
          .src = src});

    } else if (cmd == "dur") {
      string d = Util::chop(line);
      CHECK(slide != nullptr) << "dur: start slide first";
      duration = atoi(d.c_str());
      CHECK(duration > 0) << "got: " << d;

    } else if (cmd == "loop-video") {
      CHECK(slide != nullptr) << "loop-video: Add a slide first.";
      CHECK(slide->video.has_value()) << "Add a video to the slide "
        "first.";
      slide->video.value().loop = true;

    } else if (cmd == "enable-video-audio") {
      CHECK(slide != nullptr) << "enable-video-audio: Add a slide first.";
      CHECK(slide->video.has_value()) << "Add a video to the slide "
        "first.";
      slide->video.value().audio = true;

    } else if (cmd == "target") {
      CHECK(slide != nullptr) << "target: Add a slide first.";
      string sec = Util::chop(line);
      slide->target_seconds = {atoi(sec.c_str())};

    } else if (cmd == "array") {
      CHECK(slide != nullptr) << "array: start slide first";
      string los = Util::chop(line);
      string his = Util::chop(line);
      string f = Util::chop(line);
      CHECK(!f.empty() && f.find("%") != string::npos) << "array: " << f;
      int lo = atoi(los.c_str());
      int hi = atoi(his.c_str());
      for (int x = lo; x <= hi; x++) {
        AddFile(Util::Replace(f, "%", std::format("{}", x)));
      }

    } else if (cmd == "screen-width") {
      string px = Util::chop(line);
      talk.screen_width = atoi(px.c_str());
      CHECK(talk.screen_width > 0) << "Screen width needs a positive int";

    } else if (cmd == "screen-height") {
      string px = Util::chop(line);
      talk.screen_height = atoi(px.c_str());
      CHECK(talk.screen_height > 0) << "Screen height needs a positive int";

    } else {
      // Command must be a file that we can open.
      CHECK(slide != nullptr) << "start slide first (" << cmd << ")";
      AddFile(cmd);
    }
  }

  return talk;
}

void Talk::SaveJS(string_view program_dir, string_view out_dir) {
  std::string json = "/* Generated by talk.cc. Do not edit! */\n";

  AppendFormat(&json,
               "const SCREEN_WIDTH = {};\n"
               "const SCREEN_HEIGHT = {};\n",
               screen_width, screen_height);

  AppendFormat(&json, "const slides = [\n");
  for (const Slide &slide : slides) {
    AppendFormat(&json, "  {{a: [");

    for (const Frame &frame : slide.frames) {
      std::string noext = (std::string)Util::FileBaseOf(frame.filename);
      AppendFormat(&json, "{{i: '{}', d: {}}}, ",
                   noext, frame.duration);
    }
    AppendFormat(&json, "]");
    if (slide.video.has_value()) {
      const Video &v = slide.video.value();
      AppendFormat(&json,
                   ", video: {{ x: {}, y: {}, w: {}, h: {}, src: '{}'",
                   v.x, v.y, v.width, v.height, v.src);
      if (v.loop) {
        AppendFormat(&json, ", loop: true");
      }
      if (v.audio) {
        AppendFormat(&json, ", audio: true");
      }
      AppendFormat(&json, "}}");
    }

    if (slide.target_seconds.has_value()) {
      Print("Target seconds: {}\n", slide.target_seconds.value());
      AppendFormat(&json,
                   ", target: {}",
                   slide.target_seconds.value());
    }

    AppendFormat(&json, "}},\n");
  }
  AppendFormat(&json, "];\n");

  std::string talk_html = Util::DirPlus(program_dir, "talk.html");
  std::string mouse_cursor_png = Util::DirPlus(program_dir, "mouse-cursor.png");

  Util::WriteFile(Util::DirPlus(out_dir, "slides.js"), json);

  Util::WriteFile(Util::DirPlus(out_dir, "talk.html"),
                  Util::ReadFile(talk_html));
  // This should be configured in the talk?
  Util::WriteFile(Util::DirPlus(out_dir, "mouse-cursor.png"),
                  Util::ReadFile(mouse_cursor_png));
}
