
#include "talk-document.h"

#include <cmath>
#include <cstdint>
#include <format>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

#include "ansi.h"
#include "base/logging.h"
#include "base/print.h"
#include "base/stringprintf.h"
#include "image.h"
#include "periodically.h"
#include "threadutil.h"
#include "timer.h"
#include "util.h"

#include "document.h"
#include "image-document.h"

[[maybe_unused]]
static constexpr bool VERBOSE = false;

static constexpr int DEFAULT_PIXEL_WIDTH = 1920;
static constexpr int DEFAULT_PIXEL_HEIGHT = 1080;

using Transform = Document::Transform;

TalkDocument::TalkDocument(std::string_view dir) : ImageDocument(dir) {

}

void TalkDocument::GenerateOutput(
    std::string_view filename_base,
    const std::map<int, std::map<int, DocTree>> &pages) {
  Timer output_timer;

  std::string section = "slide";

  int pixel_width = DEFAULT_PIXEL_WIDTH, pixel_height = DEFAULT_PIXEL_HEIGHT;
  if (width > 0.0 && height > 0.0) {
    pixel_width = (int)std::round(width);
    pixel_height = (int)std::round(height);
  }

  std::string talk_dir = (std::string)filename_base;
  Util::MakeDir(talk_dir);

  std::string talk_filename =
    Util::DirPlus(talk_dir, (std::string)filename_base + ".talk");
  std::string talk =
    "# Generated by BoVeX\n\n";

  AppendFormat(&talk,
               "screen-width {}\n"
               "screen-height {}\n"
               "\n",
               pixel_width, pixel_height);

  // Shared status timer.
  Periodically status_per(1.0);
  Timer stickers_timer;

  int num_pages = 0;
  std::vector<std::vector<std::unique_ptr<ImagePage>>> slides;
  for (const auto &[page_idx, anim_frames] : pages) {
    std::vector<std::unique_ptr<ImagePage>> frames;
    auto pit = durations.find(page_idx);
    for (const auto &[frame_idx, doc] : anim_frames) {

      frames.push_back(std::make_unique<ImagePage>(
                           pixel_width, pixel_height, this));

      ImagePage *page = frames.back().get();
      num_pages++;

      Context context;
      context.font = GetDefaultFont();
      context.color = 0x000000FF;
      Transform identity;
      identity.dx = 0.0;
      identity.dy = 0.0;

      PlaceStickersRec(context, identity, doc, page);

      if (pit != durations.end()) {
        const auto &fdur = pit->second;
        auto fit = fdur.find(frame_idx);
        if (fit != fdur.end()) {
          page->SetDuration(fit->second);
        }
      }

      // XXX this should be slide-level. We just set
      // the target sec for every frame right now.
      if (auto target_it = targets.find(page_idx);
          target_it != targets.end()) {
        page->SetTargetSec(target_it->second);
      }

      // ditto.
      if (auto section_it = sections.find(page_idx);
          section_it != sections.end()) {
        page->SetSection(section_it->second);
      }
    }

    if (status_per.ShouldRun()) {
      if (status_per.TimesRun() == 1) {
        // The very first time, make space for the
        // progress bar.
        Print("\n");
      }

      Print(ANSI_UP "{}\n",
            ANSI::ProgressBar(slides.size(), pages.size(),
                              "Place stickers",
                              stickers_timer.Seconds()));
    }

    slides.push_back(std::move(frames));
  }

  std::mutex m;
  Timer frames_timer;
  int num_done = 0;

  const int total_frames = [&]() {
      int total = 0;
      for (const std::vector<std::unique_ptr<ImagePage>> &page : slides) {
        total += (int)page.size();
      }
      return total;
    }();

  // In case we reencounter a section, keep increasing the count.
  std::unordered_map<std::string, int> section_count;

  {
    Asynchronously async(12);
    for (int i = 0; i < (int)slides.size(); i++) {
      const std::vector<std::unique_ptr<ImagePage>> &page = slides[i];
      AppendFormat(&talk, "slide\n");

      std::optional<ImagePage::Video> video;
      for (const auto &frame : page) {
        if (frame->video.has_value()) {
          CHECK(!video.has_value()) << "Only one frame can have a video.";
          video = frame->video;
        }
      }

      if (video.has_value()) {
        const ImagePage::Video &v = video.value();
        AppendFormat(&talk,
                     "  video {} {} {} {} {}\n",
                     (int)std::round(v.x),
                     (int)std::round(v.y),
                     (int)std::round(v.width),
                     (int)std::round(v.height),
                     v.src);
        if (v.loop) {
          AppendFormat(&talk, "  loop-video\n");
        }
      }

      for (const auto &frame : page) {
        if (frame->target_sec > 0) {
          AppendFormat(&talk,
                       "  target {}\n",
                       frame->target_sec);
          // Just the first one we see.
          break;
        }
      }

      for (const auto &frame : page) {
        if (!frame->section.empty()) {
          section = frame->section;
        }
      }

      const int file_slide_num = section_count[section]++;

      for (int f = 0; f < (int)page.size(); f++) {
        const auto &frame = page[f];

        if (frame->duration != 0) {
          AppendFormat(&talk,
                       "  dur {}\n",
                       frame->duration);
        }

        const std::string framefile =
          page.size() == 1 ?
          std::format("{}-{}.png", section, file_slide_num) :
          std::format("{}-{}_{}.png", section, file_slide_num, f);
        AppendFormat(&talk,
                     "  {}\n",
                     framefile);

        async.Run([&m, &num_done, &status_per, &talk_dir,
                   &total_frames, &frames_timer,
                   fr = frame.get(), framefile]() {
            const std::string frameabsfile =
              Util::DirPlus(talk_dir, framefile);
            fr->image->Save(frameabsfile);
            {
              MutexLock ml(&m);
              num_done++;

              // TODO: Use StatusBar.
              if (status_per.ShouldRun()) {
                if (status_per.TimesRun() == 1) {
                  // The very first time, make space for the
                  // progress bar.
                  Print("\n");
                }

                Print(ANSI_UP "{}\n",
                      ANSI::ProgressBar(num_done, total_frames,
                                        "Write frames",
                                        frames_timer.Seconds()));
              }
            }
          });
      }
    }

    if (status_per.TimesRun() > 0) {
      // Remove status bar.
      Print(ANSI_UP);
    }

    Util::WriteFile(talk_filename, talk);
    // Print("Wait async...\n");
  }

  double sec = output_timer.Seconds();
  Print("Wrote {} frame{} to " AGREEN("{}") " in {}.\n",
        num_pages, num_pages != 1 ? "s" : "",
        talk_filename,
        ANSI::Time(sec));
}
