
#ifndef _ALPERTRON_ENUMS_H
#define _ALPERTRON_ENUMS_H


enum eExprErr
{
  EXPR_NUMBER_TOO_LOW = -100,
  EXPR_NUMBER_TOO_HIGH,
  EXPR_INTERM_TOO_HIGH,
  EXPR_DIVIDE_BY_ZERO,
  EXPR_PAREN_MISMATCH,
  EXPR_SYNTAX_ERROR,
  EXPR_LITERAL_NOT_INTEGER,
  EXPR_INVALID_PARAM,
  EXPR_ARGUMENTS_NOT_RELATIVELY_PRIME,
  EXPR_OUT_OF_MEMORY,
  EXPR_CANNOT_USE_X_IN_EXPONENT,
  EXPR_POLYNOMIAL_DIVISION_NOT_INTEGER,
  EXPR_DENOMINATOR_MUST_BE_CONSTANT,
  EXPR_DEGREE_TOO_HIGH,
  EXPR_EXPONENT_TOO_LARGE,
  EXPR_EXPONENT_NEGATIVE,
  EXPR_LEADING_COFF_MULTIPLE_OF_PRIME,
  EXPR_CANNOT_LIFT,
  EXPR_MODULUS_MUST_BE_GREATER_THAN_ONE,
  EXPR_MODULUS_MUST_BE_PRIME_EXP,
  EXPR_BASE_MUST_BE_POSITIVE,
  EXPR_POWER_MUST_BE_POSITIVE,
  EXPR_MODULUS_MUST_BE_NONNEGATIVE,
  EXPR_VAR_OR_COUNTER_REQUIRED,
  EXPR_MULTIPLE_VARIABLES_NOT_ACCEPTED,
  EXPR_TOO_MANY_ARGUMENTS,
  EXPR_TOO_FEW_ARGUMENTS,
  EXPR_MORE_THAN_ONE_EQUAL_SIGN,
  EXPR_EQUAL_SIGN_INSIDE_PAREN,
  EXPR_VAR_IN_EXPRESSION,
  EXPR_ARGUMENT_MUST_BE_CONSTANT,
  EXPR_CANNOT_PARSE_EXPRESSION,
  EXPR_SHORT_CIRCUIT,
  EXPR_OK = 0,
  EXPR_NOT_FOUND,
};


#endif
