// Joins particles generated by particles.exe; see paper.pdf.

#include <cstdio>
#include <format>
#include <mutex>
#include <string>
#include <vector>

#include "arcfour.h"
#include "base/logging.h"
#include "base/print.h"
#include "util.h"

#include "makejoin.h"

using namespace std;

std::mutex print_mutex;
#define Printf(fmt, ...) do {   \
  MutexLock Printf_ml(&print_mutex);    \
  printf(fmt, ##__VA_ARGS__);     \
  } while (0);

int main () {
  vector<string> dict = Util::ReadFileToLines("wordlist.asc");
  Print("{} words.\n", dict.size());
  vector<string> particles = Util::ReadFileToLines("particles.txt");
  Print("{} particles.\n", particles.size());
  ArcFour rc("portmantout");

  int total_letters = 0;
  for (const string &w : dict) {
    total_letters += w.size();
  }
  Print("{} total letters.\n", total_letters);


  vector<vector<Path>> matrix = MakeJoin(dict);

  auto SaveTable = [&matrix](const string &filename) {
    {
      FILE *f = fopen(std::format("{}.html", filename).c_str(), "wb");
      Print(f, "<!doctype html>\n"
            "<style> td {{ padding: 0 4px }} body {{ font: 13px Verdana }} </style>\n"
            "<table>");

      Print(f, "<tr><td>&nbsp;</td> ");
      for (int i = 0; i < 26; i++)
        Print(f, "<td>{:c}</td>", 'a' + i);
      Print(f, " </tr>\n");

      for (int src = 0; src < 26; src++) {
        Print(f, "<tr><td>{:c}</td> ", 'a' + src);
        for (int dst = 0; dst < 26; dst++) {
          const Path &p = matrix[src][dst];
          if (p.has) {
            Print(f, "<td>{}</td>", p.word);
          } else {
            Print(f, "<td>&mdash;</td>");
          }
        }
        Print(f, " </tr>\n");
      }

      Print(f, "</table>\n");
      fclose(f);
    }

    {
      FILE *f = fopen(std::format("{}.tex", filename).c_str(), "wb");

      auto Cols = [&f, &matrix](int col_start, int col_end) {
          Print(f, "\\noindent \\begin{{tabular}}{{c");
          for (int i = col_start; i < col_end; i++)
            Print(f, "l");
          Print(f, "}}\n");

          Print(f, " --- ");
          for (int i = col_start; i < col_end; i++)
            Print(f, "& {{" "\\bf {:c}" "}} ", 'a' + i);
          Print(f, "\\\\\n");

          for (int src = 0; src < 26; src++) {
            Print(f, "{{" "\\bf {:c}" "}} ", 'a' + src);
            for (int dst = col_start; dst < col_end; dst++) {
              const Path &p = matrix[src][dst];
              if (p.has) {
                Print(f, " & {} ", p.word);
              } else {
                Print(f, " & m--- ");
              }
            }
            Print(f, " \\\\\n");
          }

          Print(f, "\\end{{tabular}}");
      };

      Cols(0, 13);
      Print(f, "\n\n");
      Cols(13, 26);

      fclose(f);
    }
  };


  SaveTable("table-two");

  string portmantout = particles[0];
  for (int i = 1; i < particles.size(); i++) {
    CHECK(portmantout.size() > 0);
    const string &next = particles[i];
    CHECK(next.size() > 0);
    int src = portmantout[portmantout.size() - 1] - 'a';
    int dst = next[0] - 'a';
    CHECK(matrix[src][dst].has);
    const string &bridge = matrix[src][dst].word;

    // Chop one char.
    portmantout.resize(portmantout.size() - 1);
    portmantout += bridge;
    // And again.
    portmantout.resize(portmantout.size() - 1);
    portmantout += next;
  }

  printf("All done! The portmantout is assembled, of size %d. (%.1f%% efficiency)\n",
   (int)portmantout.size(),
   (portmantout.size() * 100.0) / total_letters);
  {
    FILE *f = fopen("portmantout.txt", "wb");
    fprintf(f, "%s\n", portmantout.c_str());
    fclose(f);
  }

  {
    FILE *f = fopen("portmantout.tex", "wb");
    int col = 0;
    static constexpr int MAX_COLUMN = 255;
    for (char c : portmantout) {
      fprintf(f, "%c", c);
      col++;
      if (col == MAX_COLUMN) {
  fprintf(f, "\n");
  col = 0;
      }
    }
    fprintf(f, "\n");
    fclose(f);
  }

  return 0;
}
